-- CRIAÇÃO DA TABELA USUÁRIOS
CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100),
    email VARCHAR(100),
    senha VARCHAR(255),
    tipo ENUM('comum' , 'admin')
);

-- CRIAÇÃO DA TABELA TEXTOS_ROLETA
CREATE TABLE textos_roleta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texto VARCHAR(255),
    ativo BOOLEAN DEFAULT true
);

-- INSERINDO DADOS MANUALMENTE NA TABELA
INSERT INTO usuario (id, nome, idade)
VALUES (3, 'Miguel' , 16);

-- EXCLUINDO DADOS MANUALMENTE DA TABELA
DELETE FROM usuario
WHERE id = 2;

-- ALTERANDO DADOS MANUALMENTE DA TABELA
UPDATE usuario
SET id = 1
WHERE id = 0;